{
    "request_number": 2,
    "timestamp": "2025-10-12 20:21:46",
    "model": "openai/gpt-4o-mini",
    "prompt_variant": "zero-shot-clusters",
    "total_tokens": 721,
    "avg_prob": 0.6986497715674977,
    "perplexity": 1.4313323222827221,
    "struct_metrics": {
        "avg_cyclomatic_complexity": 1.4074074074074074,
        "ast_depth": 11,
        "avg_function_size_lines": 2.8,
        "import_redundancy_ratio": 0.0
    },
    "semantic_metrics": {
        "syntax_valid": true,
        "flake8_error_count": 9,
        "mypy_error_count": 0
    },
    "execution_metrics": {
        "execution_success": false,
        "execution_time_sec": 0.65,
        "exception_type": "AttributeError",
        "exception_message": "'NoneType' object has no attribute 'submission_id'",
        "runtime_output": "Traceback (most recent call last):\n  File \"/app/main.py\", line 97, in <module>\n{'S1': 'Pending'}\n    user.submit_for_validation(found_sub)\n  File \"/app/main.py\", line 51, in submit_for_validation\n    print(f\"Submitting {submission.submission_id} for validation.\")\n                        ^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'submission_id'"
    },
    "total_credibility": 48.53
}