{
    "request_number": 16,
    "timestamp": "2025-10-12 20:10:20",
    "model": "deepseek/deepseek-chat-v3-0324",
    "prompt_variant": "zero-shot-clusters",
    "total_tokens": 2088,
    "avg_prob": 0.8564548794620518,
    "perplexity": 1.167603832939933,
    "struct_metrics": {
        "avg_cyclomatic_complexity": 2.1818181818181817,
        "ast_depth": 13,
        "avg_function_size_lines": 8.333333333333334,
        "import_redundancy_ratio": 0.3
    },
    "semantic_metrics": {
        "syntax_valid": true,
        "flake8_error_count": 47,
        "mypy_error_count": 11
    },
    "execution_metrics": {
        "execution_success": false,
        "execution_time_sec": 3.067,
        "exception_type": "EnvironmentMismatch",
        "exception_message": "Unable to open configuration file newrelic.ini.",
        "runtime_output": "/app/main.py:13: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)\n  Base = declarative_base()\nTraceback (most recent call last):\n  File \"/app/main.py\", line 229, in <module>\n    setup_newrelic_monitoring()\n  File \"/app/main.py\", line 58, in setup_newrelic_monitoring\n    newrelic.agent.initialize('newrelic.ini')\n  File \"/usr/local/lib/python3.11/site-packages/newrelic/config.py\", line 4349, in initialize\n    _load_configuration(config_file, environment, ignore_errors, log_file, log_level)\n  File \"/usr/local/lib/python3.11/site-packages/newrelic/config.py\", line 955, in _load_configuration\n    raise newrelic.api.exceptions.ConfigurationError(f\"Unable to open configuration file {config_file}.\")\nnewrelic.api.exceptions.ConfigurationError: Unable to open configuration file newrelic.ini."
    },
    "total_credibility": 39.79
}