{
    "request_number": 13,
    "timestamp": "2025-10-12 12:45:12",
    "model": "x-ai/grok-4-fast",
    "prompt_variant": "zero-shot",
    "total_tokens": 6070,
    "avg_prob": 0.8766599917115175,
    "perplexity": 1.1406930959033317,
    "struct_metrics": {
        "avg_cyclomatic_complexity": 2.2653061224489797,
        "ast_depth": 13,
        "avg_function_size_lines": 10.069767441860465,
        "import_redundancy_ratio": 0.0
    },
    "semantic_metrics": {
        "syntax_valid": true,
        "flake8_error_count": 63,
        "mypy_error_count": 2
    },
    "execution_metrics": {
        "execution_success": false,
        "execution_time_sec": 2.618,
        "exception_type": "FileNotFoundError",
        "exception_message": "[Errno 2] No such file or directory: 'historical_fabs.csv'",
        "runtime_output": "2025-10-25 18:21:58,623 - __main__ - INFO - Deleted 3 records\nTraceback (most recent call last):\n  File \"/app/main.py\", line 518, in <module>\n    app.historical.load_historical_fabs('historical_fabs.csv')\n  File \"/app/main.py\", line 397, in load_historical_fabs\n    df = pd.read_csv(file_path)\n         ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 1026, in read_csv\n    return _read(filepath_or_buffer, kwds)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 620, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 1620, in __init__\n    self._engine = self._make_engine(f, self.engine)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 1880, in _make_engine\n    self.handles = get_handle(\n                   ^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/pandas/io/common.py\", line 873, in get_handle\n    handle = open(\n             ^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: 'historical_fabs.csv'"
    },
    "total_credibility": 32.84
}